---
driver:
  name: vagrant
  customize:
      memory: 256
provisioner:
  name: chef_zero

platforms:
  - name: ub-14.04-i386
    driver:
      box: ub-14.04-i386
      box_url: https://cloud-images.ubuntu.com/vagrant/utopic/current/utopic-server-cloudimg-i386-vagrant-disk1.box

suites:
  - name: default
    run_list:
      - recipe[sdinc-jenkins::default]
    attributes:
